
# This GitHub action checks whether a new version of this package
# has been registred in the official registry.
# If so, it creates a new _release_:
# https://github.com/fonsp/PlutoUI.jl/releases

name: TagBot
on:
  issue_comment:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: [ubuntu-latest]
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
